language: node_js
node_js:
  - node
deploy:
  provider: s3
branches:
  - feature-sprint1-mglanz
  access_key_id: AKIAQ4TMT5RKLJAZ3Z7Q
  secret_access_key:
  secure: VCjA9KQA1kiEndCH4Q9dJAboOs54KNh3oDlpZuaVk8mdvzMdnq051Fy4Sx9yx8SxFpwcEnO4O1NJph03aE540Wd7TJcRqu64C6FrIGgEpfInPHwzgm3QNnuIl3JhgssGBKKC8Bs/ZsSPOv7w78eoTpzIltlktAugHYBVtHLFJeldvvX5gQMFcXn9ZMkK2xxXVqtWf4uzpnCib09GCFCPMjCIva9X5uunYAMc+y1is/NLBrBO0j7eRagDRZi9hvvcsB2rpNr4JMChL+mlbSNPYCqRXSNLi/qi0MnTd2IDrup/Syf2Jge4UIm0eOoalTA1FWJp8Ok8JbbCxiaKj3jifZYbk4H0Bp7EWzLapuWBV1OsUGqycs+SfhY9KddYEK5cnkE/HphI0AJJnU+ji5/mo24rKQKwycebPcrS2c8s/Wr6dn/daBAc+j+FT+TgDB4DJmalrfGOly8QX7TpgA7QJfIX4mraMjHU81biPd6m8DtuNwCy94X1hmvGZDjWccr7Zbt7pui1sz2gC9gE5KDwfNPkpIkNpEzjtxcLJqA7LH7FcDTp9eJtiXYYoKifkCnocBKnJRmIf8zhjqJfCIAnWePNbYGhDJ3zNgziFOnqyTyM14oYi4CCtN+wHGOaXacFvyXEO7FS1auYtBsGWD3yIZLIbl2cZRRjL/9qJcQ/mu4=
  bucket: bucketostuffs
  acl: bucket_owner_full_control
  region: us-west-2
  skip_cleanup: true
